name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-20.04
    name: Runs tests, and different linters
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout on pull request
        if: github.event_name == 'pull_request'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}\

      - name: Checkout on push to main
        if: github.event_name == 'push'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.18.3"

      - name: Run go mod vendor
        run: go mod vendor

      - name: Run tests
        run: go test ./...
